spring:
  application:
    name: springboot-micrometer-sample
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:data/micrometerdb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;AUTO_SERVER=TRUE
    username: micrometer
    password: micrometer
  liquibase:
    url: jdbc:h2:mem:micrometerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: micrometer
    password: micrometer
    default-schema: PUBLIC

logging:
  level:
    io.micrometer: DEBUG

management:
  metrics:
    tags.application: ${spring.application.name}
    export.elastic.enabled: false
    tags.region: "hamburg"
    tags.environment: "local"
    tags.subdomain: "object"
    tags.programming_language: "java"
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'

endpoints:
  prometheus.sensitive: false

